//  Message-number definitions derived from "galalias.msg"  

#define ALSKEY      1
#define CSALSKY     2
#define AHALSKY     3
#define USEALS      5
#define AHALIAS     6
#define ALSLGN      7
#define ANNOMSG     8
#define ANNOAID     9
#define ANNOCMD    10
#define CFLTPC     11
#define CFLMSGE    12
#define CFLMSGN    13
#define INTRO      15
#define INTROS     16
#define INTPMT     17
#define INTPMTS    18
#define CNOTIL     19
#define GTWALS     20
#define RMDALS     21
#define ALSHLP     22
#define ENTALS     23
#define NONSET     24
#define ALSCFLE    25
#define ALSCFLN    26
#define LONGALS    27
#define NOPROF     28
#define BADALS     29
#define ALSINU     30
#define HAVALS     31
#define ADDALS     32
#define YOUALS     33
#define NOHALS     34
#define FNDALS     35
#define THEALS     36
#define NOSALS     37
#define NOFALS     38
#define FNDUID     39
#define THEUID     40
#define NOHUID     41
#define REMALS     42
#define DELALS     43
#define NODALS     44
#define ALSNEN2    45
#define ALSCONT    46
#define ALSEMLE    47
#define ALSEMLN    48
#define NODFTALS   49
#define ALSNENAH   50
#define TIMSLC     52
