//  Message-number definitions derived from "galflmah.msg"  

#define HLMANKEY    1
#define TIMSLC      3
#define FILNFND     5
#define LIBNFND     6
#define NOVALUE     7
#define INVFNAME    8
#define FIL2LONG    9
#define UIDNFND    10
#define INVVALUE   11
#define BADDATE    12
#define ADVDATE    13
#define BADTIME    14
#define TOOLONG    15
#define INVDIR     16
#define BADID      17
#define INVNAME    18
#define GENERR     19
#define OUTOFLIB   20
#define NOTFOUND   21
#define FLAG4CPY   22
#define OTHINLIB   23
#define CONFDEL    24
#define DELDEFLT   25
#define FAILCRT    26
#define FAILUPD    27
#define FAILAPV    28
#define FAILUAPV   29
#define FAILULOG   30
#define NOJ2SELF   31
#define NOTJOIN    32
#define UNJFAIL    33
#define ALREADYJ   34
#define JOINFAIL   35
#define NOJFND     36
#define NONEJND    37
#define BADLDESC   38
#define NONE2LOG   39
#define NOOSLOG    40
#define PATHINV    41
#define FAILDEL    42
