//  Message-number definitions derived from "galfmah.msg"  

#define ROOTNAME    1
#define TIMSLC      2
#define IMGPATH     3
#define GRPMT       4
#define GRPFOR      5
#define GRPBLANK    6
#define GRPTRUNK    7
#define GRPBRNCH    8
#define GRPLEAF     9
#define GRPMTALT   10
#define GRPFOALT   11
#define GRPBLALT   12
#define GRPTRALT   13
#define GRPBRALT   14
#define GRPLEALT   15
#define PRECODE    16
#define MIDCODE    17
#define POSTCODE   18
#define ERRKEY     19
#define ERRACC     20
#define ERRUNK     21
#define GENAME     22
#define GENOPAR    23
#define GEDUP      24
#define GE2DEEP    25
#define GE2MANY    26
#define GENOTMT    27
#define GEFGONE    28
#define GE2MNYF    29
#define FENAME     30
#define FEFOROP    31
#define FEMSGLIF   32
#define FECCR      33
#define FECHGWM    34
#define FECHGRM    35
#define FECHGWA    36
#define FECHGRA    37
#define FECHGWAK   38
#define FECHGRAK   39
#define FEPFNLVL   40
#define FEACCLVL   41
#define FEECHO     42
#define FEUSE      43
#define FEDUP      44
#define FENFIL     45
#define FE2MANY    46
#define FENOFID    47
#define FENOMEM    48
#define FEFILPTH   49
#define FEDFT      50
