//  Message-number definitions derived from "galfap.msg"  

#define FAXSKY      1
#define FAXAGKY     2
#define FAXAHKEY    3
#define REALCR      4
#define VWPCHG      5
#define FAXNAV      7
#define FAXMNU      8
#define FPVMNU      9
#define BADCHO     10
#define CHGINQ     11
#define CHGINE     12
#define FAXRAT     13
#define PHONAL     14
#define ADDFAX     15
#define FAXXST     16
#define ENTFIL     17
#define YNAGIN     18
#define FAXDUP     19
#define BADFIL     20
#define RCVFNM     21
#define CNTOFN     22
#define CHNNUM     23
#define FLSTHD     24
#define CHNBSY     25
#define WT4FAX     26
#define RCVABT     27
#define OKRCVD     28
#define BADRCV     29
#define NONAVL     30
#define INVCHN     31
#define ENTDES     32
#define ENTLOK     33
#define ADDITN     34
#define OKINSD     35
#define BDINSD     36
#define OKABTD     37
#define DELFAX     38
#define NODOCS     39
#define DLSTHD     40
#define DLSTLN     41
#define BADDNM     42
#define DELSUR     43
#define OKDDEL     44
#define DELFLT     45
#define OKFDEL     46
#define CNTDEL     47
#define EDTFAX     48
#define EDTMNU     49
#define NEWNAM     50
#define NEWDES     51
#define NEWLOK     52
#define OKDUPD     53
#define DOCDUP     54
#define DOCGON     55
#define SNDPHO     56
#define SNDPHE     57
#define NOACCP     58
#define SNDTNM     59
#define SNDFNM     60
#define SNDEDT     61
#define SNDTPC     62
#define ATTDOC     63
#define DOCHLP     64
#define SDCHLP     65
#define ENTDOC     66
#define SENTDC     67
#define NOTFIL     68
#define OKFADD     69
#define LSTFUL     70
#define OKSEND     71
#define BADCRD     72
#define SNDCPY     73
#define OKSENT     74
#define CPYPHO     75
#define CPYPHE     76
#define CPYTNM     77
#define CPYTPC     78
#define TMFERR     79
#define NOSERR     80
#define NVFERR     81
#define NVPERR     82
#define NAPERR     83
#define NECERR     84
#define NAAERR     85
#define NAEERR     86
#define NAFERR     87
#define NOCFIL     88
#define NOGDNM     89
#define UADDOC     90
#define BMFFNM     91
#define FCHBSY     92
#define RCFERR     93
#define UNKERR     94
#define FDOCGN     95
#define FDCDUP     96
#define FADDSU     97
#define FEDTSU     98
#define FDELSU     99
#define FXPINF    100
#define FRCRDY    101
#define FXCRCH    102
#define VFWCHG    103
#define FXNOCH    104
#define FXSBOK    105
#define COFERR    106
#define COVERR    107
#define VDNFND    108
