//  Message-number definitions derived from "galirc.msg"  

#define IRCKEY      1
#define IRCCHG      2
#define SUPERUSR    3
#define HELPKEY     4
#define JOINKEY     5
#define KICKKEY     6
#define LISTKEY     7
#define MODEKEY     8
#define INVITKEY    9
#define MSGKEY     10
#define NAMEKEY    11
#define NICKKEY    12
#define PARTKEY    13
#define QUITKEY    14
#define WHOKEY     15
#define WHOIKEY    16
#define MEKEY      17
#define CTCPKEY    18
#define MAXIRC     20
#define MINLIST    21
#define DFTPORT    22
#define DFTSERV    23
#define BANNED     24
#define ATTRIB     25
#define IRCFULL    27
#define IRCNOA     28
#define BADCMD     29
#define CONNERR    30
#define CNTCON     31
#define CONDROP    32
#define CONDED     33
#define LUPERR     34
#define IMMERR     35
#define QUITMSG    36
#define DSRVINP    37
#define CNTRLMN2   38
#define NRMLMNU    39
#define NICKINP    40
#define SERVINP    41
#define IRCNINP    42
#define PORTINP    43
#define NOALIAS    44
#define LOOKING    45
#define CONNING    46
#define SHRTHLP    47
#define ENDHELP    48
#define CMDNOFND   49
#define KNONICK    50
#define NNONICK    51
#define INLIMBO    52
#define HLPJOIN    53
#define HLPHELP    54
#define HLPKICK    55
#define HLPLIST    56
#define HLPMSG     57
#define HLPNAME    58
#define HLPNICK    59
#define HLPPART    60
#define HLPQUIT    61
#define HLPWHO     62
#define HLPWHOI    63
#define HLPMODE    64
#define HLPINVIT   65
#define HLPME      66
#define HLPCTCP    67
#define DEFNUM     68
#define UMODE      69
#define CMODE      70
#define ON341      71
#define JONCHAN    72
#define NOJBAN     73
#define JOIN       74
#define ONNOTIC    75
#define FINGRPLY   76
#define ONINVIT    77
#define ONQUIT     78
#define WHONOPRM   79
#define WHOREPLY   80
#define ENDWHO     81
#define ONPRVACT   82
#define ONPUBACT   83
#define PART       84
#define PRIVMSG    85
#define PUBMSG     86
#define UKICK      87
#define ONKICK     88
#define ONNAME     89
#define ONNICK     90
#define ONTOPIC    91
#define BGLIST     92
#define ONLIST     93
#define ENDLIST    94
#define WHOISUSR   95
#define WHOISERV   96
#define ENDWHOIS   97
#define WHOISIDL   98
#define WHOISCHN   99
#define WHOISOPR  100
#define USRAWAY   101
#define ERRNICK   102
#define ANICKUSE  103
#define NNICKUSE  104
#define IRCWEEK   105
#define IRCWEEKS  106
#define IRCDAY    107
#define IRCDAYS   108
#define IRCHOUR   109
#define IRCHOURS  110
#define IRCMIN    111
#define IRCMINS   112
#define IRCSEC    113
#define IRCSECS   114
#define HELPSHLP  115
#define CTCPSHLP  116
#define JOINSHLP  117
#define KICKSHLP  118
#define LISTSHLP  119
#define MODESHLP  120
#define INVSHLP   121
#define MESHLP    122
#define MSGSHLP   123
#define NAMESHLP  124
#define NICKSHLP  125
#define PARTSHLP  126
#define QUITSHLP  127
#define WHOSHLP   128
#define WHOISHLP  129
#define NOCREDS   130
#define ROCREDS   131
