//  Message-number definitions derived from "GALME.msg"  

#define EMLKEY      1
#define EMSCHG      2
#define EATKEY      3
#define EATCHG      4
#define EPKCHG      5
#define RRRKEY      6
#define RRRCHG      7
#define PRIKEY      8
#define PRICHG      9
#define QIKKEY     10
#define MASSKY     11
#define LSTCHG     12
#define EDSTKY     13
#define CHGFWD     14
#define EMRCHG     15
#define EDACHG     16
#define EDKCHG     17
#define FORCCR     18
#define FMSCHG     19
#define FMRCHG     20
#define FULCHG     21
#define FKUCHG     22
#define FDLCHG     23
#define FKDCHG     24
#define FOPMFD     25
#define FORPRV     26
#define FORSYS     27
#define MSGSIZ     29
#define EMLDPTH    30
#define EMLDPTH2   31
#define DLSTPTH    32
#define DFCARP     33
#define DFLONP     34
#define DFFORP     35
#define DFQUOP     36
#define DFBRWP     37
#define DFCMTP     38
#define ESYSUID    39
#define EMLLIF     40
#define AUTQSC     41
#define SUPU2S     42
#define NUEMTO     43
#define NUEMTP     44
#define NUEMHD     45
#define NEWUEM     46
#define SUPE2U     47
#define E2UFRM     48
#define E2UTPC     49
#define E2UTXT     50
#define E2UATT     51
#define E2UANM     52
#define E2URRR     53
#define ALWEAT     54
#define ALWRRR     55
#define ALWPRI     56
#define EWRAUD     57
#define EUPAUD     58
#define ERDAUD     59
#define EDNAUD     60
#define EDAAUD     61
#define FWRAUD     62
#define FUPAUD     63
#define FRDAUD     64
#define FDNAUD     65
#define FDAAUD     66
#define FCRTAUD    67
#define FMODAUD    68
#define FDELAUD    69
#define GCRTAUD    70
#define GMODAUD    71
#define GDELAUD    72
#define MAXQSF2    73
#define FORLIF     74
#define DFTFOR     75
#define DSTDLY     76
#define STRXCK     77
#define CFMSGS     78
#define BGMCUP     79
#define BGMDLY     80
#define CFFORS     81
#define MAXFGRP    82
#define GRPNMEM    83
#define GPUID      84
#define GPTPC      85
#define GPNOTI     86
#define RRTPC      88
#define RRTEXT     89
#define SCNHDR     90
