//  Message-number definitions derived from "galmjd.msg"  

#define SYSAPP      1
#define MJDAKEY     2
#define RLSPRT      4
#define DISCHR      5
#define MJDCSCAP    6
#define MJDCSCRD    7
#define MJDCSOFF    8
#define INTRO      10
#define INTROS     11
#define INTPMT     12
#define INTPMTS    13
#define CNOTIL     14
#define INVHEX2    15
#define LESHEX     16
#define ONEWRD     17
#define INVKEY     18
#define EDTINU     19
#define INVNUM     20
#define INVTIM     21
#define ENTAPP     22
#define INVCHR     23
#define TOOLNG     24
#define DUPAPP     25
#define ENTDSC     26
#define BEGCHN     27
#define ENDCHN     28
#define ENTKEY     29
#define ENTSUR     30
#define ENTTIM     31
#define ENTHSK     32
#define ENTHMT     33
#define ENTHST     34
#define INVHST     35
#define INVBYT     36
#define THEAPP1    37
#define MODAPP     38
#define NOSAPP     39
#define EDTAPP     40
#define EDTAPP1    41
#define EDTAPP2    42
#define EDTFTR     43
#define EDTPMT     44
#define APPUPD     45
#define APPADD     46
#define MODDSC     47
#define MODBCH     48
#define MODECH     49
#define MODKEY     50
#define MODHMT     51
#define MODHST     52
#define MODSUR     53
#define MODTIM     54
#define DELAPP     55
#define DELRUS     56
#define CONFDEL    57
#define APPDEL     58
#define NONAVL     59
#define APPHDR     60
#define APPDET     61
#define ENDLST     62
#define WCHAPP     63
#define NOTAVL     64
#define NOCHNA     65
#define WT4APP     66
#define TIMOUT     67
#define INVRSP     68
#define OUTCRD2    69
#define APPTRM2    70
#define CONNTD     71
#define TODABT     72
#define LKCRED     73
#define DOORIN     74
#define YESONO     75
