//  Message-number definitions derived from "galnntpd.msg"  

#define NNTDCLS     1
#define NNTDONL     3
#define NNTDACP     4
#define NNTDREJ     5
#define NNTDPRT     6
#define NNTIP1      7
#define NNTIP2      8
#define NNTIP3      9
#define NNTIP4     10
#define NNTIP5     11
#define NNTIP6     12
#define NNTIP7     13
#define NNTIP8     14
#define NNTIP9     15
#define NNTIP10    16
#define NNTIP11    17
#define NNTIP12    18
#define NNTIP13    19
#define NNTIP14    20
#define NNTIP15    21
#define NNTIP16    22
#define MAXNNTD    23
#define AUDNNTD    24
#define AUDNNTDE   25
#define NNTDTMO    26
#define MINDSK     27
#define WRKDIR     28
#define NNTDQSI    29
#define IMAXTIM    30
#define IMINTIM    31
#define IZERTIM    32
#define IRSPTIM    33
#define INCHAN     34
#define USEXRF     35
#define NNTDSHDR   36
#define BADATT     38
#define NNTDPTN    39
#define NNTDCNM    40
#define NNTDORG    41
#define NNTDOKY    43
#define NNTDOKN    44
#define SRVFULL    45
#define SRVSHUT    46
#define NNTNOTON   47
#define NNTDMANY   48
#define NNTDLERR   49
#define NNTDANW    50
#define NNTDSYN    51
#define NNTDNTM    52
#define NNTDOK     53
#define NNTDHLP    54
#define NNTDSLV    55
#define NNTDNIMP   56
#define NNTDCNR    57
#define NNTDBYE2   58
#define NNTDTAL    59
#define NNTDNG     60
#define NNTDTMOT   61
#define NNTDNOD    62
#define NNTDINS    63
#define NNTDNAS    64
#define NNTDNGS    65
#define NNTDLST0   66
#define NNTDLST1   67
#define NNTDLST2   68
#define NNTDNSG    69
#define NNTDSLCT   70
#define NNTDLAST   71
#define NNTDNEXT   72
#define NNTDNPVA   73
#define NNTDNNXA   74
#define NNTDNSAF   75
#define NNTDNSAG   76
#define NNTDNPST   77
#define NNTDSPST   78
#define NNTDPOK    79
#define NNTDPFL    80
#define NNTDSTAT   81
#define NNTDHEAD   82
#define NNTDBODY   83
#define NNTDARTL   84
#define NNTDNGRP   85
#define NNTDNNEW   86
#define NNTDNGPN   87
#define NNTDDFLW   88
#define NNTDXOV1   89
#define NNTDXHFL   90
#define NNTDXHDR   91
#define NNTDLGRP   92
#define NNTDLFRM   93
#define NNTDLOG    95
#define NNTDLNAM   96
