//  Message-number definitions derived from "galqwk.msg"  

#define QDLKEY      1
#define QULKEY      2
#define QWKNAME     4
#define MINDLY      5
#define NEWSFL      6
#define FRMLMT      7
#define INTERPKT    8
#define INTRAPKT    9
#define INETPFX    10
#define MENU1      12
#define PRESENTR   13
#define NOTCMD     14
#define ATTONOFF   15
#define RESET      16
#define NOTRESET   17
#define RESETTO    18
#define QWKHELP    19
#define UHELP1     20
#define LACKKEY    21
#define MAKEPCKT   22
#define SCNHDR     23
#define SCNLN1     24
#define SCNLIN2    25
#define OUTCRD     26
#define CONTFOR    27
#define TOTALFND   28
#define PRSNLFND   29
#define NOTHFND    30
#define ATTNOTE    31
#define ATTNOTE1   32
#define ATTCOPY    33
#define QWKRDY1    34
#define ATTDTEXT   35
#define ATTTEXT    36
#define AINCTEXT   37
#define AREQTEXT   38
#define DLABORTD   39
#define PREVUS     40
#define FILERR     41
#define UPLDONE    42
#define SWRITTEN   43
#define EWRITTEN   44
#define FMMMGR     45
#define NOTVALID   46
#define POSTED0    47
#define POSTED1    48
#define POSTED2    49
#define POSTEDR    50
