//  Message-number definitions derived from "galregah.msg"  

#define HREGKEY     1
#define REGANONL    2
#define REGANONV    3
#define AUTHDFT     4
#define RPRFFRM     6
#define TBLDFT      7
#define DFTLSTC     8
#define MAXLSTC     9
#define ANCHOR     11
#define NEWEN      12
#define NONEWEN    13
#define COMPLT     14
#define NCOMPLT    15
#define CANDEL     16
#define NCANDEL    17
#define NOLIST1    18
#define NOLIST2    19
#define NOLIST3    20
#define NOLIST4    21
#define NOLIST5    22
#define NOLIST6    23
#define NOLIST7    24
#define NOLIST8    25
#define NOLIST9    26
#define RTARGET1   27
#define RTARGET2   28
#define RTARGET3   29
#define RTARGET4   30
#define RTARGET5   31
#define RTARGET6   32
#define RTARGET7   33
#define RTARGET8   34
#define RTARGET9   35
#define RERROR1    36
#define RERROR2    37
#define RERROR3    38
#define NOUSRIN    39
#define TIMSLC     41
