//  Message-number definitions derived from "galrlgn.msg"  

#define LGNCHG      1
#define LGNKCHG     2
#define ABTKEY      3
#define BNCKEY      4
#define ARGKEY      5
#define MAXLGN      7
#define LGNGO       8
#define CANESCP     9
#define CONTWT     10
#define ABTSTGG    11
#define ABTSEC     12
#define AUDCON     13
#define AUDDSC     14
#define LGNHOST    16
#define LGNHLP1    17
#define LGNHLPP1   18
#define LGNHLP2    19
#define LGNHLPP2   20
#define LGNMANY    21
#define NOUSR      22
#define NOESCOD    23
#define UNKSWCH    24
#define CANTBNC    25
#define CANTPRM    26
#define BADUSR     27
#define NOALIAS    28
#define NOHOST     29
#define BADESC     30
#define LOOKING    31
#define CONNING    32
#define LUPERR     33
#define CONNED     34
#define DISCHELP   35
#define BINDERR    36
#define SOCKERR    37
#define IOCLERR    38
#define CONNERR    39
#define RCVERR     40
#define SNDERR     41
#define IRUPT      42
#define SVREND     43
#define SVRDISC    44
#define ABORTED    45
#define CONNRFSD   46
#define CONTMO     47
#define UNKNOWN    48
#define CANTESP    49
#define NOPRT      50
#define PRTREB     51
#define NOXTRN     52
#define NOTAG      53
