//  Message-number definitions derived from "GALSCP.msg"  

#define SLPKEY      1
#define CSLKEY      2
#define PPPKEY      3
#define LONKEY      4
#define MULSKEY     5
#define PROXKEY     6
#define DYNKEY      7
#define CONFKEY     8
#define KEEPKEY     9
#define SCPCHGL    10
#define SCPCHGR    11
#define SCPPMIN    12
#define SCPAMIN    13
#define DUALFACT   14
#define SCPMINCG   15
#define REALCR     16
#define CREDZAP    17
#define SAFEZAP    18
#define SCPMAX     20
#define USERIPS    21
#define SCPIP      22
#define SCPMASK    23
#define SCPMTU     24
#define SCPDMODE   25
#define SCPALN     26
#define SCPATB     27
#define MAXPXP     28
#define PFXLOGON   29
#define SCPAHLO3   31
#define SCPPHLO3   32
#define SCPNOPAG   33
#define SCPBAD     34
#define SCPNOLON   35
#define SCPLOCK    36
#define SCPFULL    37
#define SCPONE     38
#define SCPIVAL    39
#define SCPDLOCK   40
#define SCPPLOCK   41
#define SCPDPLCK   42
#define SCPNODYN   43
#define SCPERR     44
#define SCPABORT   45
#define SCPTERM    46
#define SCPNOCNF   47
#define SCPCONF    48
#define LSTHDR     49
#define LSTBDY     50
#define LSTFTR     51
#define LSTABT     52
#define SCPNONE    53
#define SCPSYNTX   54
#define SCPRERR    55
#define SCPCONFL   56
#define SCPONNOW   57
#define SCPRANG2   58
#define SCPHAS     59
#define SCPHASN    60
#define SCPALR     61
#define SCPNEW     62
