//  Message-number definitions derived from "GALSMTP.msg"  

#define SMTKEY      1
#define SMTCHG      2
#define SMTATKY     3
#define SMTATCH     4
#define SMTPKCH     5
#define SMTPONL     7
#define SMTPFX      8
#define SMTNAM      9
#define SMTDSC     10
#define SMTXMP     11
#define SMTHELP    12
#define SMTOBD     13
#define SMTRSD     14
#define SMTUND     15
#define SMTNOUT    16
#define SMTTMO     17
#define SMTAUD     18
#define SMTAUDE    19
#define SMTIHST    20
#define SMTTMZ     21
#define USESMRT    22
#define SMTSMRT    23
#define SMRTPORT   24
#define SMTRQA     25
#define AUTHNAME   26
#define AUTHPASS   27
#define ATTINC     29
#define SMTDNE     30
#define SMTEXP     31
#define SMTEXP1    32
#define SMTRERR    33
#define SMTPMWR    34
#define BADATT     35
#define BININC1    36
#define ASCINC1    37
#define SMTLOG     39
#define SMTLNAM    40