//  Message-number definitions derived from "galsmtpd.msg"  

#define SMTDKEY     1
#define SMTDONL     3
#define SMTDREJ     4
#define SMTDPRT     5
#define MAXSMTD     6
#define SMTDTMO     7
#define MINDSK      8
#define LIMSIZ      9
#define MAXMSG     10
#define WRKDIR     11
#define SMTDQSI    12
#define IMAXTIM    13
#define IMINTIM    14
#define IZERTIM    15
#define IRSPTIM    16
#define INCHAN     17
#define AUDSMTD    18
#define AUDSMTDE   19
#define SMTDREV    20
#define MAXHOPS    21
#define SMTDSHDR   22
#define SMTDHOST   23
#define SMTDLOCR   24
#define SMTDLOCF   25
#define AUDSMTDR   26
#define SMTDBLOK   27
#define AUDSMTDB   28
#define SMTDCVTF   29
#define SMTDPUID   30
#define MAILAL1    31
#define MAILAL2    32
#define MAILAL3    33
#define MAILAL4    34
#define MAILAL5    35
#define MAILAL6    36
#define MAILAL7    37
#define MAILAL8    38
#define MAILAL9    39
#define MAILAL10   40
#define MAILAL11   41
#define MAILAL12   42
#define MAILAL13   43
#define MAILAL14   44
#define MAILAL15   45
#define MAILAL16   46
#define SMTDPTN    48
#define SMTDCNM    49
#define SMTDORG    50
#define SMTDEML    51
#define SMTDRDY    53
#define SRVFULL    54
#define SRVDENY    55
#define SRVSHUT    56
#define SMTNOTON   57
#define SMTDMANY   58
#define SMTDTAL    59
#define SMTDOSQ    60
#define SMTDLERR   61
#define SMTDRVER   62
#define SMTDRVNO   63
#define SMTDOK     64
#define SMTDROVR   65
#define SMTDNON    66
#define SMTDNRLY   67
#define SMTD2BIG   68
#define SMTDFULL   69
#define SMTDTMOT   70
#define SMTDHOP    71
#define SMTDHLP2   72
#define SMTDNIMP   73
#define SMTDSYN    74
#define SMTDSML    75
#define SMTDBYE    76
#define SMTDLTL    77
#define SMTDUSRH   78
#define SMTDUSR    79
#define SMTDUNF    80
#define SMTDARQ    81
#define SMTDAPL1   82
#define SMTDMIER   83
#define SMTDATTN   84
#define SMTDNKY    85
#define SMTDLOG    87
#define SMTDLNAM   88
