//  Message-number definitions derived from "GALTLC.msg"  

#define TLCCCR      1
#define TLCOVR      2
#define SWTFRM      3
#define CSWTO       4
#define MODKEY      5
#define UNLKEY      6
#define NPAYMX      7
#define MAXFRE      8
#define DBRDKY      9
#define FILKEY     10
#define TLCAKEY    11
#define NSWCHX     13
#define REQINT     14
#define TINPSZ     15
#define INTRO      17
#define TLCPMT     18
#define TLCHLP     19
#define ENTTLC     20
#define BYSELF     21
#define ONEOTH     22
#define TWOOTH     23
#define SOMOTH     24
#define SEVOTH     25
#define CHNTPC     26
#define STOPIC     27
#define URMODR     28
#define URMODO     29
#define IROEPI     30
#define LVITLC     31
#define CHTOFF     32
#define CHTNPS     33
#define NOTMOD     34
#define NUIHLP     35
#define TLKSQU     36
#define YOUSQU     37
#define CHIMSQ     38
#define HESSQU     39
#define YOUUSQ     40
#define CHEUSQ     41
#define HESUSQ     42
#define NOMCH1     43
#define NOOVRS     44
#define ANOMOD     45
#define MODLIV     46
#define BMODER     47
#define BGNCON     48
#define ENDCON     49
#define RESIGN     50
#define ALRMOD     51
#define UBMODR     52
#define NEWMOD     53
#define UNLSTC     54
#define NSCNHDR    55
#define LSTCHN     56
#define WHATCH     57
#define OUTORG     58
#define PRVLCH     59
#define CANTLV     60
#define CANTGO     61
#define CANTGOCS   62
#define YOURCH     63
#define PAYONL     64
#define NANNOY     65
#define NANNOYDB   66
#define LEFTCH     67
#define CAMEIN     68
#define NMTALK     69
#define MSGSNT     70
#define WHSSNT     71
#define NPAYXC     72
#define WHSFMT     73
#define WHSNHR     74
#define AMBIG      75
#define PAMBIG     76
#define WHSTO      77
#define CHAFMT     78
#define NCHSLF     79
#define NOCHAA2    80
#define NOCHCS2    81
#define GONCHA     82
#define ACCPCH     83
#define ENTCHA     84
#define CHAL2M     85
#define CHAREQ     86
#define CREQOK     87
#define EXICH2     88
#define TLCHUP     89
#define OCHHP2     90
#define PFNWRD     91
#define RAUNCH     92
#define URINVS     93
#define SNDLN0     94
#define SNDNHR     95
#define SNDSLF     96
#define SNDNCS     97
#define SNDRCV     98
