//  Message-number definitions derived from "galtnt.msg"  

#define TNTCHG      1
#define TNTKCHG     2
#define PORTKEY     3
#define ABTKEY      4
#define BNCKEY      5
#define MAXTNT      7
#define TNTGO       8
#define CONTWT      9
#define ABTSTG     10
#define ABTSEC     11
#define XITSTG     12
#define AUDCON     13
#define AUDDSC     14
#define TNTHOST    16
#define TNTSHOST   17
#define TNTHLP1    18
#define TNTHLPP1   19
#define TNTHLP4    20
#define TNTHLPP4   21
#define TNTCONFL   22
#define TNTNOPAG   23
#define TNTMANY    24
#define TNTZMANY   25
#define CANTBNC    26
#define CANTPRT    27
#define BADPRT     28
#define LOOKING    29
#define CONNING    30
#define LUPERR     31
#define CONNED     32
#define DISCHELP   33
#define DISCAHLP   34
#define NOSGA      35
#define AYTREPL    36
#define OPOVFL     37
#define SOCKERR    38
#define IOCLERR    39
#define CONNERR    40
#define IMMERR     41
#define RCVERR     42
#define SNDERR     43
#define IRUPT      44
#define SVREND     45
#define SVRDISC    46
#define ABORTED    47
#define CONTMO     48
