//  Message-number definitions derived from "galwebd.msg"  

#define WEBONL      1
#define WEBREJ      2
#define WEBPORT     3
#define AXSFIL      4
#define AXSFILN     5
#define AGTFIL      6
#define AGTFILN     7
#define ERAFIL      8
#define ERAFILN     9
#define MAXWEBD    10
#define WEBROOT    11
#define IMGROOT    12
#define IMGPFIX    13
#define DFTFIL     14
#define AUDWEB     15
#define AUDWEBE    16
#define WEBPATC    17
#define WEBDZONE   18
#define REQQUE     19
#define CHUSTAT    20
#define NONCHU     21
#define FILEGET    23
#define FILEGET2   24
#define HDRBUST    25
#define BDYBUST    26
#define FOPFAIL    27
#define FWFAIL     28
#define FRFAIL     29
#define ICAGOOF    30
#define TIMEOUT    31
#define REQFMT     32
#define NOTFND     33
#define BADFSPEC   34
#define NOTMOD     35
#define BADMAP     36
#define BADMAPRF   37
#define MAPREDIR   38
#define MAPNOT     39
#define MAPNOCLK   40
#define BADMETH    41
#define OFFLINE    42
#define SYSSHUT    43
#define SYSFULL    44
#define WEBFULL    45
#define DIRREDIR   46
