//  Message-number definitions derived from "wgserver.msg"  

#define STAKEY      1
#define GAGTKEY     2
#define ALWKNOCK    3
#define CSNUMXRF    5
#define JFLAGOFF    6
#define JFLAGRUN    7
#define JFLAGADV    8
#define UIDNOG1    10
#define ACCSUS     11
#define MEMONL     12
#define NONEWU     13
#define NONEWA     14
#define IMMEDL     15
#define NOTIME     16
#define ALRDON     17
#define PTOOSML    18
#define BADPSW     19
#define CANTCPSW   20
#define NTOOSML    21
#define NPROFAN    22
#define CPROFAN    23
#define A1TOOSML   24
#define A1PROFAN   25
#define A2TOOSML   26
#define A2PROFAN   27
#define A3PROFAN   28
#define VTOOSML    29
#define VPROFAN    30
#define INVSYS     31
#define BADANSI    32
#define BADSWD     33
#define BADSLN     34
#define BADEPRF    35
#define INVBDY     36
#define INVSEX     37
#define BADLANG    38
#define CANTCLNG   39
#define INVUID     40
#define CANTALTR   41
#define NOTALWD    42
#define SUPAID1    44
#define MMAID1     45
