//  Message-number definitions derived from "wgsedtm.msg"  

#define FSEMHI      1
#define EDTMNU2     3
#define EDTMNUT     4
#define EDTMPMT     5
#define EDPWKS      6
#define EDTPMT2     7
#define EDTPMTT     8
#define EDTPMT2M    9
#define EDTPMTTM   10
#define GETTPC     11
#define ENTTXT     12
#define CNTENT     13
#define HLPAVL     14
#define HLPAVLWT   15
#define HLPWKS     16
#define HLPQUT     17
#define HLPTPC     18
#define HLPSAV     19
#define HLPAPP     20
#define HLPLIS     21
#define HLPCHG     22
#define HLPRTY     23
#define HLPDEL     24
#define HLPINS     25
#define HLPNEW2    26
#define CNOTIL     27
#define INVLIN     28
#define CRLRDS     29
#define RWCHLN     30
#define REPLAC     31
#define RPLCWW     32
#define NOMCHF     33
#define NLNRDS     34
#define EWCHLN     35
#define EDITLN     36
#define DWCHLN     37
#define UPLMOD     38
#define DELLIN     39
#define YORN       40
#define IWCHLN     41
#define INSLIN     42
#define NUSURB     43
#define IMPNF2     44
#define CUSURB     45
#define TOOBIG     46
#define TOOBIG2    47
#define LINOVR     48
#define LPROFAN    49
#define FSEHDR     50
#define FSETRL     51
#define FSEHLP2    53
#define FSEOPN1    54
#define FSEOP21    55
#define FSEUPL     56
#define FSEOPFN    57
#define EXTNDH     58
#define EXTND2     59
#define EXTND3     60
#define EXTND4A    61
#define EXTND5     62
#define FSEGMNM    63
#define FSEIMR     64
#define FSENIM     65
#define FSEQYN     66
#define FSEBYE     67
#define FSE2LE     68
#define FSETTY     69
#define FSETPC     70
#define FSEFID     71
#define FSEPRO     72
#define FIXTOP     73
#define BIGFIL3    74
#define FSEPRT     75
#define FSEPAGT    76
#define FSEPAGM    77
#define FSEPAGB    78
