//  Message-number definitions derived from "wgsftf.msg"  

#define ASULOCK     1
#define XMULOCK     2
#define YMULOCK     3
#define YGULOCK     4
#define ZMULOCK     5
#define KMULOCK     6
#define FIMLOCK     7
#define ASDLOCK     8
#define LSDLOCK     9
#define XMDLOCK    10
#define YMDLOCK    11
#define YGDLOCK    12
#define ZMDLOCK    13
#define KMDLOCK    14
#define VEWLOCK    15
#define FEXLOCK    16
#define MAXTAGS    18
#define XBYTTO     19
#define XBLKTO     20
#define XRETRY     21
#define X25TMO     22
#define ZTZONE     23
#define ZXWINDOW   24
#define KTXWIN     25
#define KRCWIN     26
#define KTXTMO     27
#define KRCTMO     28
#define KTXRETRY   29
#define KRCRETRY   30
#define FXPREF     31
#define FXSUFF     32
#define ALWAIT     33
#define BINZAP     34
#define ASCZAP     35
#define RIPADL     36
#define FTGASK     38
#define FUPASK     39
#define PRTCHC     40
#define PRTTWO     41
#define PRTRCHC    42
#define NOPROTS    43
#define FTGASKT    44
#define FTGASKB    45
#define FPFOOTD    46
#define FPFOOTU    47
#define FTGASKH    48
#define FUPASKH    49
#define FTGASKVH   50
#define FTGASKTH   51
#define BADCHC     52
#define ASCHDR     53
#define BGNSND     54
#define BGNRCV     55
#define BGNSAS     56
#define BGNRAS     57
#define BGNSMANY   58
#define BGNRMANY   59
#define FINXFR     60
#define ZERXFR     61
#define SHTXFR     62
#define LSTWHY     63
#define VEWAGN1    64
#define ABTSND     65
#define ABTRCVF    66
#define ABTRCV     67
#define ABTASC     68
#define SRETRY     69
#define SRETRYV    70
#define RRETRY     71
#define TAGSFA     72
#define BRFTAG     73
#define TSHLST     74
#define TSHBUST    75
#define TAGWDO     76
#define LASTTAG    77
#define FULLWRN    78
#define MULJOIN    79
#define MJBARF     80
#define MJNO       81
#define CANTFIND   82
#define NOTAGS     83
#define TAGPRT     84
#define TAGPRTI    85
#define TPCHCN     86
#define TPCHCS     87
#define TPCHCP     88
#define TPCHCA     89
#define TPCHCL     90
#define TPCHC      91
#define NOWTAG     92
#define TPUNLAST   93
#define TAGFULL    94
#define FTFLOST    95
#define BANGOFF2   96
#define BANGFAST   97
#define BANGAVT    98
#define BANGNOW    99
#define FIRPATH   100
#define FIRHELP   101
#define FIRNOT    102
#define FIRBOMB   103
#define FIRREF    104
#define FIRASK    105
#define FIREASK   106
#define FIRCPY    107
#define FIRECPY   108
#define FIRCEX    109
#define FIRDOSR   110
#define FIRDOSW   111
#define FIRFULL   112
#define FIRAGN    113
#define FEXPATH   114
#define FEXHELP   115
#define FEXLONG   116
#define FEXNODIR  117
#define FEXNOFIL  118
#define FEXING    119
#define FEXEROP   120
#define FEXFULL   121
#define FEXDOSW   122
#define FEXDOSR   123
#define FEXCEX    124
#define LOFICP    125
#define FTFUPHDR  126
#define FTFDNHDR  127
#define FTFTGHDR  128
#define FTFTRL1   129
#define FTFTRL2   130
