//  Message-number definitions derived from "wormsg.msg"  

#define CSMGRKY     1
#define AHMGRKY     2
#define WLKEY       3
#define WLCHG       4
#define WLATKY      5
#define WLATCH      6
#define WLPKCH      7
#define WLRRKY      8
#define WLRRCH      9
#define WLPRKY     10
#define WLPRCH     11
#define WFKEY      12
#define WFCHG      13
#define WFATKY     14
#define WFATCH     15
#define WFPKCH     16
#define AHMGRON    18
#define USEWL      19
#define ACTINP     20
#define WLPFX      21
#define WLNAME     22
#define WLDESC     23
#define WLEXMP     24
#define WLHELP     25
#define WFPFX      26
#define WFNAME     27
#define WFDESC     28
#define WFEXMP     29
#define WFHELP     30
#define WLROOT     31
#define RCVTIM     32
#define EMLPUSH    33
#define LIMEATT    34
#define MAXEASZ    35
#define USEXRF     36
#define AUTAPV     37
#define LIMFATT    38
#define MAXFASZ    39
#define NETCANO    40
#define NETCANI    41
#define NETMODO    42
#define NETMODI    43
#define AUDSND     44
#define AUDSERR    45
#define AUDRCV     46
#define AUDRERR    47
#define AUDMGR     48
#define AUDMERR    49
#define AUDGEN     50
#define AUDGERR    51
#define USEBGI     52
#define AUDIMP     53
#define AUDIERR    54
#define IMAXTIM    55
#define IMINTIM    56
#define IRSPTIM    57
#define INCHAN     58
#define EIMPNOT    60
#define PIMPNOT    61
#define FIMPNOT    62
#define ATTREJ     63
#define ERRWAIT    65
#define MAXCTIM    66
#define FCPYPC     67
#define FADDPC     68
#define FCHKPC     69
#define MAXNTFY    70
#define LSTSLC     71
#define IMPERR     72
#define IENFND     73
#define IESQU      74
#define IESQS      75
#define IEUNK      76
#define CFGNONAM   77
#define CFGROOM    78
#define MEUNK      79
#define MENOC      80
#define MEBUSY     81
#define MERST      82
#define MECAN      83
#define MEDISC     84
#define MESEQ      85
#define MESPC      86
#define MENFND     87
#define MEACC      88
#define MEMAX      89
#define MEXST      90
#define MEFNAM     91
#define MENOMO     92
#define MEUSE      93
#define AESPC      94
#define AENSYS     95
#define AEUNK      96
#define MODSND     97
#define MODRCV     98
#define MODIMP     99
#define MODMGR    100
#define MODGEN    101
#define STWCONN   102
#define STWDISC   103
#define STIDLE    104
#define STERROR   105
#define STRESET   106
#define STCANCEL  107
#define STSNDST   108
#define STSNDATT  109
#define STSNDMSG  110
#define STRCVRQE  111
#define STRCVRQF  112
#define STRCVWT   113
#define STRCVATT  114
#define STRCVMSG  115
#define STRCVIMP  116
#define STIMPRD   117
#define STIMPSND  118
#define STIMPDIS  119
#define STMGRDET  120
#define STMGRCFG  121
#define STMGRCRT  122
#define STMGRMOD  123
#define STMGRDEL  124
#define STMGRGAC  125
#define STMGRNDA  126
#define STMGRSAC  127
#define STGENSFL  128
#define STGENRFL  129
#define LSTMT     130
#define LSTCFG    131
#define LSTUSED   132
#define LSTINV    133
#define ACCVIEW   134
#define ACCREAD   135
#define ACCWRT    136
#define ACCMGR    137
#define ACCUNK    138
#define NOFORS    139
#define CFGBADSZ  140
